import { simpleGit } from 'simple-git'
import { getAuthenticatedCloneUrl, createPullRequest } from './github.js'
import { logProgress, updateTicketStatus, updateAgentRun } from './supabase.js'
import fs from 'fs/promises'
import path from 'path'

// Job passed via environment variable
interface AgentJob {
  ticketId: string
  agentRunId: string
  repoUrl: string
  branchName: string
  title: string
  description: string
}

async function main() {
  // Parse job from environment
  const jobJson = process.env.AGENT_JOB
  if (!jobJson) {
    console.error('AGENT_JOB environment variable not set')
    process.exit(1)
  }

  const job: AgentJob = JSON.parse(jobJson)
  const workspace = `/tmp/workspace-${job.ticketId}`

  console.log(`Starting agent for ticket: ${job.title}`)
  console.log(`Repo: ${job.repoUrl}`)
  console.log(`Branch: ${job.branchName}`)

  try {
    await logProgress(job.agentRunId, job.ticketId, 'started', `Agent starting for: ${job.title}`)

    // 1. Clone repository
    await logProgress(job.agentRunId, job.ticketId, 'thinking', 'Cloning repository...')
    const authUrl = await getAuthenticatedCloneUrl(job.repoUrl)
    await simpleGit().clone(authUrl, workspace)
    console.log('Repository cloned')

    // 2. Create branch
    const git = simpleGit(workspace)
    await git.checkoutLocalBranch(job.branchName)
    await logProgress(job.agentRunId, job.ticketId, 'action', `Created branch: ${job.branchName}`)
    console.log(`Created branch: ${job.branchName}`)

    // 3. Run agent loop
    await logProgress(job.agentRunId, job.ticketId, 'thinking', 'Analyzing codebase and planning implementation...')

    // TODO: Integrate OpenCode SDK here
    // For now, create a simple placeholder file to demonstrate the flow
    const placeholderPath = path.join(workspace, 'AGENT_PLACEHOLDER.md')
    await fs.writeFile(placeholderPath, `# Agent Task

**Ticket:** ${job.title}

**Description:**
${job.description}

---

This file was created by the ADD agent as a placeholder.
In the full implementation, the OpenCode SDK will analyze the codebase
and make real changes based on the ticket description.

Generated at: ${new Date().toISOString()}
`)

    await logProgress(job.agentRunId, job.ticketId, 'file_edit', 'Created AGENT_PLACEHOLDER.md')

    // 4. Commit changes
    await git.add('.')
    await git.commit(`[ADD Agent] ${job.title}`)
    await logProgress(job.agentRunId, job.ticketId, 'commit', 'Changes committed')
    console.log('Changes committed')

    // 5. Push branch
    await logProgress(job.agentRunId, job.ticketId, 'action', 'Pushing to GitHub...')
    await git.push('origin', job.branchName, ['--set-upstream'])
    console.log('Pushed to GitHub')

    // 6. Create PR
    await logProgress(job.agentRunId, job.ticketId, 'thinking', 'Creating pull request...')
    const prUrl = await createPullRequest(
      job.repoUrl,
      job.branchName,
      `[ADD Agent] ${job.title}`,
      `## Summary

This PR was created by the ADD (Agent Driven Development) platform.

**Original ticket:**
${job.description}

---

*Generated by ADD Agent*`
    )
    console.log(`PR created: ${prUrl}`)

    // 7. Update ticket and agent run
    await logProgress(job.agentRunId, job.ticketId, 'complete', `PR created: ${prUrl}`, { prUrl })
    await updateTicketStatus(job.ticketId, 'review', prUrl)
    await updateAgentRun(job.agentRunId, 'complete')

    console.log('Agent completed successfully!')
    process.exit(0)

  } catch (error) {
    console.error('Agent failed:', error)
    await logProgress(job.agentRunId, job.ticketId, 'error', String(error))
    await updateAgentRun(job.agentRunId, 'failed', String(error))
    process.exit(1)
  }
}

main()
